### ISSUE TITLE
New style local_options() doesn't work with NULL

### ISSUE THREAD

**Issue by hadley** [r-lib/withr#156] opened 2020-12-01 22:02 UTC
``` r
f1 <- function() {
  withr::local_options(x = 1)
  print(getOption("x"))
  withr::local_options(x = NULL)
  print(getOption("x"))
}
f1()
#> [1] 1
#> [1] 1

f2 <- function() {
  withr::local_options(list(x = 2))
  print(getOption("x"))
  withr::local_options(list(x = NULL))
  print(getOption("x"))
}
f2()
#> [1] 2
#> NULL
```

<sup>Created on 2020-12-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jimhester** [comment] 2021-04-16 12:25
The root cause seems to be

``` r
utils::modifyList(list(), list(x = NULL))
#> list()
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

I guess we can write our own version of modifyList to work around this.

**Comment by jimhester** [comment] 2021-04-16 12:44
Fixed by https://github.com/r-lib/withr/commit/ae0ef58ee3f02964219818d4466dd6c496e395ad

**Closed by jimhester** 2021-04-16 12:44 UTC
