### ISSUE TITLE
defer() doesn't run deferred code in some cases

### ISSUE THREAD

**Issue by wch** [r-lib/withr#147] opened 2020-08-28 20:10 UTC
I've found that if the function calls `capture.output(print(env))`, then the deferred code does not run.

Here's an example:

```R
defer_test <- function(env = parent.frame()) {
  # If this line is commented out, the deferred code runs
  cat(capture.output(print(env)))
  withr::defer(
    cat("Running deferred code!\n"),
    envir = env
  )
}

f <- function() {
  defer_test()
}

f()
#> <environment: 0x7fbe7cca8780>
```

**Comment by jimhester** [comment] 2020-09-01 17:54
I can reproduce this, but I don't know the cause, guess it is related to the internals of `capture.output()` and / or `sink()`

**Comment by wch** [comment] 2020-09-01 20:00
It looks like it has something to do with evaluating `env` in the `capture.otuput()`, and then using it as the `envir` for `defer()`.

Here's a smaller example:

```R
defer_test <- function(env = parent.frame()) {
  capture.output(env)
  withr::defer(
    cat("Running deferred code!\n"),
    envir = env
  )
}
f <- function() {
  defer_test()
}
f()  # No output
```

And here's the same code, except that `defer()` is called with `envir=parent.frame()`. This one works:

```R
defer_test2 <- function(env = parent.frame()) {
  capture.output(env)
  withr::defer(
    cat("Running deferred code!\n"),
    envir = parent.frame()
  )
}
g <- function() {
  defer_test2()
}
g()
#> Running deferred code!
```

**Comment by wch** [comment] 2020-09-02 03:32
I managed to make a more minimal example. If `env` is `eval()`ed, then the same problem happens. However, if `env` is first evaluated normally, then the deferred code does run.


```R
defer_test <- function(force_env, env = parent.frame()) {
  if (force_env) {
    env
  }

  eval(quote(env), environment())
  
  withr::defer(
    cat("Running deferred code!\n"),
    envir = env
  )
}

f <- function(force_env) {
  defer_test(force_env)
}

f(T)
#> Running deferred code!

f(F) # No output

```

**Comment by lionel-** [comment] 2020-09-02 06:17
That is extremely mysterious :)

**Comment by lionel-** [comment] 2020-09-02 06:27
oh of course, the promise gets forced in the fake `eval()` context whose parent frame is the `base::eval()` closure. So there's no way around it, we have to force `env` in these cases so the promise resolves correctly.

Usually this is not an issue because stack-sensitive functions like `environment()` climb the stack to look for a closure stack frame that produced a promise. But the R level `eval()` sets a fake closure context (that's why these `on.exit()` tricks work to begin with, or why you can `return()` from an expression evaluated with `base::eval()`) and that trips up the stack frame search.

**Comment by lionel-** [comment] 2020-09-02 07:33
We could fix it in R by using `delayedAssign()` instead of `eval()` to evaluate the `...` expressions.

Another way would be to use `...elt()` within `withVisible()`, this way there is no need for capturing dots and evaluating them manually.  AFAICT the only reason the dots are substituted and evaluated with `eval()` is to capture visibility for each expression. Instead, we could do something along these lines:

```r
fn <- function(...) {
  n <- ...length()
  out <- vector("list", n)

  for (i in seq_len(n)) {
    out[[i]] <- withVisible(...elt(i))
  }

  out
}
```

The problem with this approach is that `...elt()` forces visibility off. Which I think is not right because it should have the same behaviour as evaluating arguments the normal way, e.g. with `..1` etc. So that would have to be changed as well. I'll submit patches.

**Comment by jimhester** [comment] 2020-09-02 12:14
`...elt()` nad `..length()` are only available in R 3.5+ right?

**Comment by lionel-** [comment] 2020-09-02 12:32
Right but why do you ask?

**Comment by jimhester** [comment] 2020-09-02 12:45
Because we need to support at least 3.3, so how could we use them?

**Comment by lionel-** [comment] 2020-09-02 12:47
oh I was just discussing how to fix `capture.output()` upstream in the utils package. Until it's fixed in all versions of R I think there is nothing we can really do except forcing `env` before calling `capture.output()`.

**Comment by jimhester** [comment] 2020-09-02 12:49
Oh I see, I misunderstood!

**Comment by wch** [comment] 2020-09-02 13:09
Is it really worth it to change `capture.output()`? This problem could potentially happen with any function that `eval()`s the expression passed into it, and `capture.output()` is just one of many.

Perhaps the documentation for `defer()` and the [blog post](https://www.tidyverse.org/blog/2020/04/self-cleaning-test-fixtures/) with examples could be edited to mention this potential problem, and how to avoid it.

**Comment by lionel-** [comment] 2020-09-02 13:45
I think the implementation of `capture.output()` would be cleaner if purely SE. If NSE is required, then `base::eval()` should only be used when you want data-masking, or a returnable context (i.e. for testthat blocks). Otherwise you should use `rlang::eval_bare()` or `delayedAssign()` for evaluation. (It would also be great to have an `eval0()` primitive function in base R for this sort of things.)

Using an SE approach also fixes the scoping of dots. Currently if you try to wrap `capture.output()` you get:

```r
wrapper <- function(...) {
    capture.output(..., type = "output")
}
local({
    foo <- 1
    wrapper(foo)
})
#> Error in withVisible(expr) : object 'foo' not found
```

With an SE implementation you get the expected result:

```r
local({
    foo <- 1
    wrapper(foo)
})
#> [1] "[1] 1"
```

I think it's worth making this sort of changes because it makes the R language more predictable.

**Comment by lionel-** [comment] 2020-09-09 07:38
Fixed in R-devel.

**Comment by lionel-** [comment] 2022-02-24 15:14
This edge case seems too specific to be added to the documentation. It should be rare to use NSE functions in low level functions that use `defer()`. Hopefully this github issue serves as sufficient documentation.

**Closed by lionel-** 2022-02-24 15:14 UTC
Labels: documentation
