### ISSUE TITLE
CRAN notice: issues need fixing before 2024-07-31

### ISSUE THREAD

**Issue by llrs** [r-lib/withr#263] opened 2024-07-23 13:04 UTC
There is a deadline in withr that is fast approaching in 8 days and I don't see activity since January, in addition it is the day before CRAN team leaves for holidays so there isn't much time if the submission is not successful and close to the deadline.

The problems seem easy to fix: 
1) A warning for documentation mismatches: Check: for code/documentation mismatches 
2) An error in a test file (which can be harder to fix): cannot open file '/Volumes/Builds/packages/big-sur-arm64/Rlib/4.4/cli/R/sysdata.rdb': No such file or directory

Is there anything we could do to help?

**Comment by chainsawriot** [comment] 2024-07-29 14:00
The second one appears to be false positive to me.

The first one is due to this update to the `pdf()` in R-devel.

https://github.com/r-devel/r-svn/blob/10fd4bd431f4d9ebf85dc94dacd7bc305d36d3fe/doc/NEWS.Rd#L45-L48

whilst here, the documentation inherits the parameters from `pdf()`

https://github.com/r-lib/withr/blob/334415234c4b049d125c1a0b47a20d682daef9ad/R/devices.R#L119

One solution is to hardcode the documentation.

**Comment by llrs** [comment] 2024-07-29 14:16
1) Writing down the parameter would be a nice solution. But I think updating the docs, just `roxygen2::document()`, would be easy and enough to fix it.
2) It has been constant in the last few days. I don't think it is a false positive.

**Comment by chainsawriot** [comment] 2024-07-29 15:26
The output of `roxygen2::document()` depends on R version if `@inheritParams grDevices::pdf` is used. If we run `roxygen2::document()` on r-devel (thus adding "timestamp" and friends), the output will break `r-release` and `r-oldrel`.

The first one does look like an incorrect installation of `cli` (usually it can be fixed by either reinstalling or restarting). But I might be wrong.

**Comment by hadley** [comment] 2024-07-29 17:49
Seems likely that the cli problem is a false positive.

Hopefully we're not at risk removal for not updating docs for a function that was only changed two weeks ago 😬.

**Comment by hadley** [comment] 2024-07-29 17:50
@lionel- for R-devel, I think it would be nice to default to reproducible PDFs, i.e. setting `timestamp` and `author` to `FALSE`.

**Comment by lionel-** [comment] 2024-07-30 05:32
FYI y'all I got the email the day I left for vacations with a 2 week notice!

That's only the first deadline though so withr is not at risk from being removed from CRAN anytime soon.

**Comment by lionel-** [comment] 2024-07-31 11:42
On its way to CRAN.

**Closed by lionel-** 2024-07-31 11:42 UTC

**Comment by llrs** [comment] 2024-07-31 13:36
Thanks! I hope you enjoyed your holidays! 
The new deadline (2024-08-18) I assume is because checks haven't catch up with the new version yet.

**Comment by lionel-** [comment] 2024-07-31 13:39
I think so, that new deadline was on the page before the release was sent.
